[package]
name = "transit"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3.3.3"
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "chrono", "uuid"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
